In [21]:
import pandas as pd
temporal_rf_univariado = pd.read_csv('temporal_rf_univariada.csv',encoding='utf-8',sep=',',index_col=[0])
temporal_rf_univariado['TECNICA'] = 'RF (UNIVARIADA)'

temporal_rf_todas_var  = pd.read_csv('temporal_rf_todas_var.csv',encoding='utf-8',sep=',',index_col=[0])
temporal_rf_todas_var['TECNICA'] = 'RF (TODAS VAR.)'

temporal_rf_var_selec  = pd.read_csv('temporal_rf_var_selecionadas.csv',encoding='utf-8',sep=',',index_col=[0])
temporal_rf_var_selec['TECNICA'] = 'RF (VAR. SELEC.)'

temporal_rl_univariado = pd.read_csv('temporal_rl_univariada.csv',encoding='utf-8',sep=',',index_col=[0])
temporal_rl_univariado['TECNICA'] = 'RL (UNIVARIADA)'

temporal_rl_todas_var  = pd.read_csv('temporal_rl_todas_var.csv',encoding='utf-8',sep=',',index_col=[0])
temporal_rl_todas_var['TECNICA'] = 'RL (TODAS VAR.)'

temporal_rl_var_selec  = pd.read_csv('temporal_rl_var_selecionadas.csv',encoding='utf-8',sep=',',index_col=[0])
temporal_rl_var_selec['TECNICA'] = 'RL (VAR. SELEC.)'

temporal_mlp_univar      = pd.read_csv('temporal_mlp_univariada.csv',encoding='utf-8',sep=',',index_col=[0])
temporal_mlp_univar['TECNICA'] = 'MLP (UNIVARIADA)'

temporal_mlp_var_selec   = pd.read_csv('temporal_mlp_var_selecionadas.csv',encoding='utf-8',sep=',',index_col=[0])
temporal_mlp_var_selec['TECNICA'] = 'MLP (VAR. SELEC.)'

temporal_mlp_todas_var   = pd.read_csv('temporal_mlp_todas_var.csv',encoding='utf-8',sep=',',index_col=[0])
temporal_mlp_todas_var['TECNICA'] = 'MLP (TODAS VAR.)'

temporal_lstm_univar     = pd.read_csv('temporal_lstm_univariada.csv',encoding='utf-8',sep=',',index_col=[0])
temporal_lstm_univar['TECNICA'] = 'LSTM (UNIVARIADA)'

temporal_lstm_var_selec  = pd.read_csv('temporal_lstm_var_selecionadas.csv',encoding='utf-8',sep=',',index_col=[0])
temporal_lstm_var_selec['TECNICA'] = 'LSTM (VAR. SELEC.)'

temporal_lstm_todas_var  = pd.read_csv('temporal_lstm_todas_var.csv',encoding='utf-8',sep=',',index_col=[0])
temporal_lstm_todas_var['TECNICA'] = 'LSTM (TODAS VAR.)'

resultados_temporal = pd.concat([temporal_rf_univariado, temporal_rf_todas_var,  temporal_rf_var_selec,
                       temporal_rl_univariado,  temporal_rl_todas_var,  temporal_rl_var_selec,
                       temporal_mlp_univar,     temporal_mlp_var_selec, temporal_mlp_todas_var,
                       temporal_lstm_univar,    temporal_lstm_var_selec,temporal_lstm_todas_var])

resultados_temporal.round(2)

,parametro,mape_treino,rmse_treino,std_rmse_treino,r_quad_treino,mape_teste,rmse_teste,std_rmse_teste,r_quad_teste,TECNICA
0,ph,0.44,0.01,0.00,0.92,2.49,0.03,0.00,0.15,RF (UNIVARIADA)
1,coliformes,2.89,0.22,0.01,0.91,48.82,1.45,0.04,0.01,RF (UNIVARIADA)
2,dbo,6.44,0.09,0.01,0.92,13.94,0.25,0.02,0.09,RF (UNIVARIADA)
3,fosforo,24.94,0.04,0.00,0.92,64.63,0.11,0.01,0.12,RF (UNIVARIADA)
4,od,29.90,0.06,0.01,0.92,37.22,0.13,0.01,0.13,RF (UNIVARIADA)
...,...,...,...,...,...,...,...,...,...,...
3,fosforo,82.80,0.12,0.00,0.15,73.11,0.11,0.00,0.03,LSTM (TODAS VAR.)
4,od,93.42,0.17,0.00,0.10,44.39,0.13,0.00,0.08,LSTM (TODAS VAR.)
5,solido,6.33,0.17,0.00,0.22,4.01,0.12,0.00,0.06,LSTM (TODAS VAR.)
6,temperatura,1.85,0.03,0.00,0.09,2.11,0.03,0.00,0.03,LSTM (TODAS VAR.)
7,turbidez,14.63,0.22,0.00,0.12,12.34,0.22,0.00,0.01,LSTM (TODAS VAR.)

In [22]:
resultados_temporal.round(2).to_csv (r'C:\Users\Anderson\predicaoagua\src\src_experimentos_dissertaÃ§Ã£o_log\resultados_log_csv\resultados_predicao_temporal.csv', index = True, header=True)

In [31]:
import pandas as pd
espaco_temporal_rf_univariado = pd.read_csv('espaco_temporal_rf_univariada.csv',encoding='utf-8',sep=',',index_col=[0])
espaco_temporal_rf_todas_var  = pd.read_csv('espaco_temporal_rf_todas_var.csv',encoding='utf-8',sep=',',index_col=[0])
espaco_temporal_rf_var_selec  = pd.read_csv('espaco_temporal_rf_var_selecionadas.csv',encoding='utf-8',sep=',',index_col=[0])

espaco_temporal_rl_univariado = pd.read_csv('espaco_temporal_rl_univariada.csv',encoding='utf-8',sep=',',index_col=[0])
espaco_temporal_rl_todas_var  = pd.read_csv('espaco_temporal_rl_todas_var.csv',encoding='utf-8',sep=',',index_col=[0])
espaco_temporal_rl_var_selec  = pd.read_csv('espaco_temporal_rl_var_selecionadas.csv',encoding='utf-8',sep=',',index_col=[0])

espaco_temporal_mlp_univar      = pd.read_csv('espaco_temporal_mlp_univariada.csv',encoding='utf-8',sep=',',index_col=[0])
espaco_temporal_mlp_var_selec   = pd.read_csv('espaco_temporal_mlp_var_selecionadas.csv',encoding='utf-8',sep=',',index_col=[0])
espaco_temporal_mlp_var_selec['tecnica'] = 'MLP (var. selec.)'

espaco_temporal_mlp_todas_var   = pd.read_csv('espaco_temporal_mlp_todas_var.csv',encoding='utf-8',sep=',',index_col=[0])

espaco_temporal_lstm_univar     = pd.read_csv('espaco_temporal_lstm_univariada.csv',encoding='utf-8',sep=',',index_col=[0])
espaco_temporal_lstm_var_selec  = pd.read_csv('espaco_temporal_lstm_var_selecionadas.csv',encoding='utf-8',sep=',',index_col=[0])
espaco_temporal_lstm_var_selec['tecnica'] = 'LSTM (var. selec.)'

espaco_temporal_lstm_todas_var  = pd.read_csv('espaco_temporal_lstm_todas_var.csv',encoding='utf-8',sep=',',index_col=[0])

resultados_espaco_temporal = pd.concat([espaco_temporal_rf_univariado, espaco_temporal_rf_todas_var,espaco_temporal_rf_var_selec,
                       espaco_temporal_rl_univariado,espaco_temporal_rl_todas_var,espaco_temporal_rl_var_selec,
                       espaco_temporal_mlp_univar,espaco_temporal_mlp_var_selec,espaco_temporal_mlp_todas_var,
                       espaco_temporal_lstm_univar,espaco_temporal_lstm_var_selec,espaco_temporal_lstm_todas_var])

resultados_espaco_temporal.round(2)

,tecnica,parametro,mape_treino,rmse_treino,std_rmse_treino,r_quad_treino,mape_teste,rmse_teste,std_rmse_teste,r_quad_teste
0,RF (Univar.),ph,3.59,0.03,0.00,0.10,3.19,0.03,0.00,0.00
1,RF (Univar.),coliformes,70.69,1.74,0.19,0.27,88.96,1.86,0.23,0.08
2,RF (Univar.),dbo,20.16,0.24,0.01,0.52,21.85,0.27,0.02,0.21
3,RF (Univar.),fosforo,87.64,2.10,0.00,0.20,87.16,2.13,0.01,0.00
4,RF (Univar.),od,35.14,0.28,0.01,0.05,35.08,0.27,0.01,0.00
...,...,...,...,...,...,...,...,...,...,...
3,LSTM (Todas var.),fosforo,489.81,0.66,0.00,0.12,611.93,0.65,0.00,0.02
4,LSTM (Todas var.),od,30.86,0.22,0.00,0.04,43.54,0.27,0.00,0.00
5,LSTM (Todas var.),solido,62.70,1.51,0.00,0.15,63.34,1.55,0.00,0.00
6,LSTM (Todas var.),temperatura,35.31,0.49,0.00,0.01,35.95,0.50,0.00,0.02
7,LSTM (Todas var.),turbidez,38.14,0.61,0.00,0.00,38.51,0.64,0.00,0.01

In [32]:
resultados_espaco_temporal.round(2).to_csv (r'C:\Users\Anderson\predicaoagua\src\src_experimentos_dissertaÃ§Ã£o_log\resultados_log_csv\resultados_predicao_espaco_temporal.csv', index = True, header=True)

In [33]:
import pandas as pd
espacial_univariada = pd.read_csv('espacial_univariada.csv',encoding='utf-8',sep=',',index_col=[0])
espacial_todas_var  = pd.read_csv('espacial_todas_var.csv',encoding='utf-8',sep=',',index_col=[0])
espacial_var_selecionadas  = pd.read_csv('espacial_var_selecionadas.csv',encoding='utf-8',sep=',',index_col=[0])

resultados_espacial = pd.concat([espacial_univariada, espacial_todas_var,espacial_var_selecionadas])

resultados_espacial.round(2)

,parametro,AM,mape_treino,rmse_treino,std_rmse_treino,r_quad_treino,mape_teste,rmse_teste,std_rmse_teste,r_quad_teste
0,ph,RL (Univariado),0.16,0.00,0.00,0.07,0.15,0.00,0.00,0.11
1,ph,RF (Univariado),0.13,0.00,0.00,0.37,0.17,0.00,0.00,0.06
2,ph,MLP (Univariado),2.09,0.02,0.01,0.15,2.11,0.02,0.01,0.09
3,ph,LSTM (Univariado),1.26,0.01,0.01,0.12,1.27,0.01,0.01,0.10
4,coliformes,RL (Univariado),48.36,1.08,0.00,0.04,53.00,1.14,0.00,0.01
...,...,...,...,...,...,...,...,...,...,...
23,solido,LSTM (Var. selec.),2.60,0.08,0.01,0.18,2.66,0.08,0.00,0.09
24,turbidez,RL (Var. selec.),12.98,0.22,0.00,0.00,12.97,0.22,0.00,0.00
25,turbidez,RF (Var. selec.),9.25,0.16,0.06,0.42,14.32,0.25,0.03,0.01
26,turbidez,MLP (Var. selec.),12.04,0.20,0.04,0.11,13.44,0.24,0.02,0.00
27,turbidez,LSTM (Var. selec.),12.48,0.21,0.03,0.06,13.22,0.23,0.02,0.00

In [34]:
resultados_espacial.round(2).to_csv (r'C:\Users\Anderson\predicaoagua\src\src_experimentos_dissertaÃ§Ã£o_log\resultados_log_csv\resultados_predicao_espacial.csv', index = True, header=True)